services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
